 wolf:
  display: 人狼
  faction: wolf
  channel:
    - wolf
    - day
  victim:
    -
      - number_faction.wolf >= number_faction.villager
  skill:
    -
      limitE: 1
      limitA: -1
      level: 50
      // up to 255
      amp: 100
      // from 0 to 100
      succeeded:
        -
          if: [[]]
          do: []
      failed:
        -
          if: [[]]
          do: []
      description: []
  ability:
    -
      call: who act_to whom @args(arg1,arg2,arg3,...)
      life: 1
      wait: 1
      level: 50
      amp:
      succeeded:
        -
          if: [[]]
          do: []
      failed:
        -
          if: [[]]
          do: []
      description: []
  description: []